// Mocks generated by Mockito 5.4.6 from annotations
// in tech_c/test/mocks/home_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:tech_c/features/home/domain/models/pokemon_model.dart' as _i9;
import 'package:tech_c/features/home/domain/usecases/home_usecase.dart' as _i11;
import 'package:tech_c/features/home/external/datasources/home_datasource.dart'
    as _i6;
import 'package:tech_c/features/home/infrastructure/repositories/home_repository.dart'
    as _i3;
import 'package:tech_c/global/app_core/domain/models/either.dart' as _i7;
import 'package:tech_c/global/app_core/failures/app_failure.dart' as _i8;
import 'package:tech_c/global/network/app_http.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeRepository_1 extends _i1.SmartFake
    implements _i3.HomeRepository {
  _FakeHomeRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppHttp].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppHttp extends _i1.Mock implements _i4.AppHttp {
  MockAppHttp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<T>> post<T>(
    String? path, {
    bool? useBaseUrl = true,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #useBaseUrl: useBaseUrl,
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #useBaseUrl: useBaseUrl,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> get<T>(
    String? path, {
    bool? useBaseUrl = true,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #useBaseUrl: useBaseUrl,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #useBaseUrl: useBaseUrl,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> put<T>(
    String? path, {
    bool? useBaseUrl = true,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #useBaseUrl: useBaseUrl,
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #useBaseUrl: useBaseUrl,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);

  @override
  _i5.Future<_i2.Response<T>> delete<T>(
    String? path, {
    bool? useBaseUrl = true,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #useBaseUrl: useBaseUrl,
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i5.Future<_i2.Response<T>>.value(
              _FakeResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #useBaseUrl: useBaseUrl,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<T>>);
}

/// A class which mocks [HomeDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeDatasource extends _i1.Mock implements _i6.HomeDatasource {
  MockHomeDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<Map<String, dynamic>> fetchPokemonData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPokemonData, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>>
  loadPokemonData() =>
      (super.noSuchMethod(
            Invocation.method(#loadPokemonData, []),
            returnValue:
                _i5.Future<
                  _i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>
                >.value(
                  _i10.dummyValue<
                    _i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>
                  >(this, Invocation.method(#loadPokemonData, [])),
                ),
          )
          as _i5.Future<
            _i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>
          >);
}

/// A class which mocks [HomeUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeUsecase extends _i1.Mock implements _i11.HomeUsecase {
  MockHomeUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HomeRepository get homeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepository),
            returnValue: _FakeHomeRepository_1(
              this,
              Invocation.getter(#homeRepository),
            ),
          )
          as _i3.HomeRepository);

  @override
  _i5.Future<_i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>>
  loadPokemonData() =>
      (super.noSuchMethod(
            Invocation.method(#loadPokemonData, []),
            returnValue:
                _i5.Future<
                  _i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>
                >.value(
                  _i10.dummyValue<
                    _i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>
                  >(this, Invocation.method(#loadPokemonData, [])),
                ),
          )
          as _i5.Future<
            _i7.Either<_i8.AppGenericFailure, List<_i9.PokemonModel>>
          >);
}
